version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - asasalint
    - asciicheck
    - errchkjson
    - copyloopvar
    - forcetypeassert
    - makezero
    - nilerr
    - unparam
    - unconvert
    - wastedassign
    - usestdlibvars
    - gosec
