// Package internal — Xray SDK helpers (Phase 3 of the migration plan).
//
// This file replaces the `jf xr curl` subprocess wrappers from xray_cli.go with direct calls
// through the JFrog Xray SDK's HTTP client. The structure mirrors jfrog-client-go's
// XscInnerService (xray/services/xsc/xsc.go) — a thin wrapper around an authenticated
// *jfroghttpclient.JfrogHttpClient that exposes typed methods for Xray APIs.
//
// CRITICAL: There is NO typed SDK method for synchronous reads of /api/v1/violations.
// Confirmed by grep across jfrog-client-go@v1.55.0 — no ViolationsService, no GetViolations.
// ReportService.Violations() creates an ASYNC report job and is not what we need.
// The XrayService.GetViolations() method uses mgr.Client().SendPost() directly against
// /api/v1/violations, which is the only realistic path (mirrors XscInnerService internally).
package internal

import (
	"encoding/json"
	"fmt"

	"github.com/jfrog/jfrog-client-go/auth"
	"github.com/jfrog/jfrog-client-go/http/jfroghttpclient"
	xrayServices "github.com/jfrog/jfrog-client-go/xray/services"
	"github.com/jfrog/jfrog-client-go/utils/log"
)

// ---------------------------------------------------------------------------
// Request body types (Phase 0 stubs, kept here for Phase 3 parity)
// ---------------------------------------------------------------------------

// violationsRequest is the body sent to POST /api/v1/violations.
type violationsRequest struct {
	Filters violationsFilters `json:"filters"`
}

type violationsFilters struct {
	WatchName     string              `json:"watch_name"`
	ViolationType string              `json:"violation_type"`
	Resources     violationsResources `json:"resources"`
	IncludeDetails bool               `json:"include_details"`
}

type violationsResources struct {
	Artifacts []violationsArtifact `json:"artifacts"`
}

type violationsArtifact struct {
	Repo string `json:"repo"`
	Path string `json:"path"`
}

// ---------------------------------------------------------------------------
// XrayService — thin wrapper around an authenticated Xray HTTP client.
// Mirrors jfrog-client-go/xray/services/xsc/xsc.go:XscInnerService.
// ---------------------------------------------------------------------------

// XrayService wraps an authenticated *jfroghttpclient.JfrogHttpClient and
// provides typed methods for interacting with the Xray API. It is constructed
// from an existing XrayServicesManager's Client() and ServiceDetails, ensuring
// JWT tokens are properly initialized (Phase 1) and retries/backoff are inherited
// from the SDK client (no silent bypass).
type XrayService struct {
	client      *jfroghttpclient.JfrogHttpClient
	XrayDetails auth.ServiceDetails
}

// NewXrayService creates an XrayService from an authenticated Xray HTTP client
// and service details. The client is expected to already carry JWT bearer tokens
// generated by CreateInitialRefreshableTokensIfNeeded (Phase 1).
func NewXrayService(client *jfroghttpclient.JfrogHttpClient, details auth.ServiceDetails) *XrayService {
	return &XrayService{
		client:      client,
		XrayDetails: details,
	}
}

// ---------------------------------------------------------------------------
// GetViolations — synchronous read of POST /api/v1/violations
// ---------------------------------------------------------------------------

// GetViolations queries Xray for current violations on an artifact, returning
// vulnerability data alongside malicious_package status from the same response.
// This is the synchronous read of POST /api/v1/violations — no async report job.
//
// watchName filters results to those relevant to a specific Xray watch (required;
// without it the API returns all violations in the project, potentially thousands).
// repo and path identify the artifact within Artifactory storage.
func (xs *XrayService) GetViolations(watchName, repo, path string) ([]violationWithMalicious, error) {
	if watchName == "" || repo == "" || path == "" {
		return nil, fmt.Errorf("watchName, repo, and path are all required")
	}

	req := violationsRequest{
		Filters: violationsFilters{
			WatchName:     watchName,
			ViolationType: "Security",
			Resources: violationsResources{
				Artifacts: []violationsArtifact{{Repo: repo, Path: path}},
			},
			IncludeDetails: true,
		},
	}
	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal violations request: %w", err)
	}

	log.Info(fmt.Sprintf("[XrayService] GET /api/v1/violations url=%s repo=%s path=%s watch=%s body=%s",
		xs.XrayDetails.GetUrl(), repo, path, watchName, string(body)))

	httpDetails := xs.XrayDetails.CreateHttpClientDetails()
	httpDetails.SetContentTypeApplicationJson()
	url := fmt.Sprintf("%s/api/v1/violations", xs.XrayDetails.GetUrl())

	resp, respBody, err := xs.client.SendPost(url, body, &httpDetails)
	if err != nil {
		return nil, fmt.Errorf("POST /api/v1/violations failed: %w", err)
	}

	log.Info(fmt.Sprintf("[XrayService] resp status=%d body_len=%d body=%s", resp.StatusCode, len(respBody), string(respBody)))

	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("Xray returned status %d: %s", resp.StatusCode, string(respBody))
	}

	type violationResponse struct {
		TotalViolations int               `json:"total_violations"`
		Violations      []xrayViolation   `json:"violations"`
	}
	var parsed violationResponse
	if err := json.Unmarshal(respBody, &parsed); err != nil {
		return nil, fmt.Errorf("failed to parse violations response: %w", err)
	}

	var results []violationWithMalicious
	for _, v := range parsed.Violations {
		vuln := xrayServices.Vulnerability{
			IssueId:    v.IssueID,
			Summary:    v.Description,
			Severity:   v.Severity,
			Technology: v.Type, // Store type in Technology field for downstream classification
		}

		if v.Properties != nil {
			if propsMap, ok := v.Properties.(map[string]interface{}); ok {
				if cveId, ok := propsMap["cve"].(string); ok && cveId != "" {
					vuln.Cves = []xrayServices.Cve{
						{Id: cveId, Cwe: extractCwesFromProperties(propsMap)},
					}
				}
			}
		}

		if v.ExtendedInformation != nil {
			vuln.ExtendedInformation = &xrayServices.ExtendedInformation{
				FullDescription: v.ExtendedInformation.FullDescription,
			}
		}

		results = append(results, violationWithMalicious{
			Vulnerability:    vuln,
			MaliciousPackage: v.MaliciousPackage,
		})
	}
	return results, nil
}
